server:
  port: 8080
spring:
  application:
    name: blog-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 106.14.136.83:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
             allow-credentials: true
             allowed-origins:
             - "http://localhost:8081"
             allowed-headers: "*"
             allowed-methods:
             - OPTIONS
             - GET
             - POST
      discovery:
        locator:
          enabled: true
      routes:
      - id: blog-admin #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001          #匹配后提供服务的路由地址
        uri: lb://blog-admin #匹配后提供服务的路由地址
        predicates:
        - Path=/admin/*/**        # 断言，路径相匹配的进行路由
        #filters:
        #- StripPrefix=1

      - id: blog-oauth #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001          #匹配后提供服务的路由地址
        uri: lb://blog-oauth #匹配后提供服务的路由地址
        predicates:
        - Path=/oauth/**         # 断言，路径相匹配的进行路由
        #filters:
        #- StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:5555/getPublicKey'