server:
  port: 8080
spring:
  application:
    name: blog-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.114.172.114:80
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: blog-admin #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001          #匹配后提供服务的路由地址
        uri: lb://blog-admin #匹配后提供服务的路由地址
        predicates:
        - Path=/admin/test/**        # 断言，路径相匹配的进行路由
        filters:
        - StripPrefix=1

      - id: blog-oauth #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001          #匹配后提供服务的路由地址
        uri: lb://blog-oauth #匹配后提供服务的路由地址
        predicates:
        - Path=/oauth/oauth/**         # 断言，路径相匹配的进行路由
        filters:
        - StripPrefix=1