###############################################################################
#配置文件已持久化到nacos配置中心
##############################################################################
spring:
  profiles:
    active: dev
